language: java
install: true

jdk:
  - oraclejdk8

script:
  - GRADLE_OPTS=-Dfile.encoding=windows-1252 ./gradlew clean build --stacktrace --no-daemon

before_cache:
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - find $HOME/.gradle/caches -name '*.lock' | rm -f

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
